apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads-pv
spec:
  capacity:
    storage: 500Gi # Adjust as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - basalt
