apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblibmanager-config
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
