apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headphones-config
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi # Adjust as needed
  storageClassName: local-path