apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pinchflat
resources:
  - namespace.yaml
  - config-pv.yaml
  - config-pvc.yaml
  - downloads-pv.yaml
  - downloads-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
