
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prowlarr-custom-indexers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prowlarr-custom-indexers
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    resourceNames:
      - prowlarr
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prowlarr-custom-indexers
subjects:
  - kind: ServiceAccount
    name: prowlarr-custom-indexers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prowlarr-custom-indexers
