apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-basalt
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              memory: "0Gi"
              cpu: "0"
          ports:
            - containerPort: 5055
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: TZ
              value: "Asia/Tashkent"
            - name: PORT
              value: "5055"
          volumeMounts:
            - name: jellyseerr-config
              mountPath: /app/config
      volumes:
        - name: jellyseerr-config
          persistentVolumeClaim:
            claimName: jellyseerr-config
