apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi # Adjust as needed
  storageClassName: local-storage
