apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti # Adjust as needed
  storageClassName: local-storage
