apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-media
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: media
              mountPath: /media
              readOnly: true
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
