apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.1.126
    path: /mnt/user/Media
    readOnly: true
  mountOptions:
    - fsc
