apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pinchflat-app
spec:
  project: default
  source:
    repoURL: git@github.com:ozeliurs/PirateFleet.git
    path: pinchflat
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
