apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-openvpn-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
