apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-openvpn
  template:
    metadata:
      labels:
        app: transmission-openvpn
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-basalt
      containers:
        - name: transmission-openvpn
          image: haugene/transmission-openvpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          ports:
            - containerPort: 9091
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9091
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: transmission-openvpn-config
              mountPath: /config
            - name: transmission-openvpn-downloads
              mountPath: /data
          env:
            - name: LOCAL_NETWORK
              value: 10.0.0.0/8
            - name: OPENVPN_CONFIG
              value: france
            - name: OPENVPN_PROVIDER
              value: PIA
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transmission-openvpn-secret
                  key: OPENVPN_PASSWORD
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: transmission-openvpn-secret
                  key: OPENVPN_USERNAME
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
      volumes:
        - name: transmission-openvpn-config
          persistentVolumeClaim:
            claimName: transmission-openvpn-config
        - name: transmission-openvpn-downloads
          nfs:
            server: 192.168.1.126
            path: /mnt/user/Downloads
