apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-openvpn-downloads-pv
spec:
  capacity:
    storage: 500Gi # Adjust the size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/transmission
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-media
