apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-openvpn-downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Gi
