---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-openvpn-secret
  namespace: default
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgC8vliqdKonCnTapjBpTO5Cyin+FmmSUZUXi71/8JgDXKIIcNQBpLlZmJJnxwIdRh6uZtsCPuL0UaiOtQrMAzjoLsap60g2+M9CKAZaYgKe4Y+XIdN7A7oi1Ai10Yyd7THMy1FC0mdt59aJsPTOp05ofAdx8gxCeKYWkZ+ra6Y6zHfelP8uFU+3l4tOo7jC/x2P5aDB2ESlPJjTbAx9c2OM/nl7C+BYsWyLNFGM/0xqQ8SHKDzHwHZeQfuRizzxeCbWOSSi73Tn9LnpFCXXSeCTwaOUXgkRdS69PwXw75XOC6jrUKCe0a9nq+GOGJkuSqZm4XaeKS2flGKyqdFQSq6k0YHQfVSh+xnIj6f3UCYm7Vqwu/MJJHoKR6+5s7iFJMBSqpRTcS0Bn5NzpudchpDbYyIiB+djnRBFFv3JG57BvWEBOhFZXfu7r+cHuExcfLpVSNoIO6xc04+iUBaPGFI4gY7WgfQjzIxf/wpGbjI9MEwv5Pz2c8tMLbHCTSjQrCq/ulyS5gbSHLv+5hAWvU+4AVZxYf/6A4HaVkALNDHc/oSjJcg3Qyrbt6BD7E5y63a2GKTVZUu9RpxGmiohrjS6NARYOio1KapCQrsWSD6hTFTJBtzi4t6AKnOBe55iBi5tLt0j99cczkymW9+efsChnfcHTfM7R1FtIPWL6TUSGCliBX40+tEDDAf9LoCMitg33FcpAiti9jky
    OPENVPN_USERNAME: AgCZb8sFUJSfiVS3H+CGO4C7qCVu2ENznFWGQcizF2+uh7CYE45zlJoqe5OmiI6wcGedAOl3F4XiiP6Q3n6e78Akam+KBMJi2fzWTc7rAHa3hAK/w60G6b3ZOyVyYkOrDVzr+zKjMqvuFCxuH5hmhjDygMWg8rrdMORcvDihtZhgTGix9GDcLz27kBqbLPn0iRSiqCOOilOxTwTNWgB8byLQi68fLWjk+83O4W8rHkCBhtSsCNaZpoo5yC8rqwJ2Nz5+xvVhlxzEdWUyEqgxuuV81Dd75+ztsV6lwio8FaLwBPJ/Im8Kwr75ovQnLlFYy7sA1smQvW56AlGTwlbM6YGOCT0CeGR29ggL/x96iBg2bn+1TAV9fIONZ+G7YVaafqRmIDsfiR9xszYCFiwmXBKwrSfVMXRQyLCiJP7YqObq3gNABHZsRv4g8s9Pq3fDRw28uWQZIXmmR0nbg+rWVvFKQGlT9K/UZETVHHiWmQnpdSRCX4X/FZCYYm0J74Uh7x+VZuXoS7V+syjeCyydMtyFQiTWYl0Lra8R5a8zSV0XbzDD5cYlSTSlNS52l8xAvE0U7qDSGTyIqDs/LZRw7D7ceROv5LteZYlv4jL4dkMUDWzP9jOIzQbYJvR1qeyEM5qBvudQasGN2WKDVD+p/iGPMOxwG97d4BzJPpgz+pugB0P7r8IaKm57/dxnWiOFs6LcNC1hbev8wA==
  template:
    metadata:
      creationTimestamp: null
      name: transmission-openvpn-secret
      namespace: default
    type: Opaque
