apiVersion: v1
kind: PersistentVolume
metadata:
  name: wizarr-config-pv
spec:
  capacity:
    storage: 1Gi # Adjust as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/appdata/wizarr
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - basalt
